<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class JemaatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jemaat')->insert([
            ['stambuk' => '000101', 'keluarga_id' => '0001', 'nama' => 'budi santoso', 'alias' => 'budi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1980-05-10', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000102', 'keluarga_id' => '0001', 'nama' => 'siti aminah', 'alias' => 'siti', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1982-07-22', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000103', 'keluarga_id' => '0001', 'nama' => 'anita santoso', 'alias' => 'ani', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '2012-05-10', 'hubungankeluarga' => 'anak', 'namaayah' => 'budi santoso', 'namaibu' => 'siti aminah', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000201', 'keluarga_id' => '0002', 'nama' => 'andi pratama', 'alias' => 'andi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'bandung', 'tanggallahir' => '1975-01-15', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000202', 'keluarga_id' => '0002', 'nama' => 'rina hartati', 'alias' => 'rina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'bandung', 'tanggallahir' => '1978-03-27', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000203', 'keluarga_id' => '0002', 'nama' => 'fahmi pratama', 'alias' => 'fahmi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'bandung', 'tanggallahir' => '2007-11-05', 'hubungankeluarga' => 'anak', 'namaayah' => 'andi pratama', 'namaibu' => 'rina hartati', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000301', 'keluarga_id' => '0003', 'nama' => 'agus supriyadi', 'alias' => 'agus', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1983-09-13', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000302', 'keluarga_id' => '0003', 'nama' => 'lina supriyadi', 'alias' => 'lina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1985-04-20', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000303', 'keluarga_id' => '0003', 'nama' => 'nanda supriyadi', 'alias' => 'nanda', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '2003-07-08', 'hubungankeluarga' => 'anak', 'namaayah' => 'agus supriyadi', 'namaibu' => 'lina supriyadi', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000401', 'keluarga_id' => '0004', 'nama' => 'rendi kusuma', 'alias' => 'rendi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'medan', 'tanggallahir' => '1979-06-11', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000402', 'keluarga_id' => '0004', 'nama' => 'tari kusuma', 'alias' => 'tari', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'medan', 'tanggallahir' => '1981-02-25', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000403', 'keluarga_id' => '0004', 'nama' => 'niko kusuma', 'alias' => 'niko', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'medan', 'tanggallahir' => '2001-12-30', 'hubungankeluarga' => 'anak', 'namaayah' => 'rendi kusuma', 'namaibu' => 'tari kusuma', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000501', 'keluarga_id' => '0005', 'nama' => 'wahyu setiawan', 'alias' => 'wahyu', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'semarang', 'tanggallahir' => '1982-05-14', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000502', 'keluarga_id' => '0005', 'nama' => 'rina setiawan', 'alias' => 'rina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'semarang', 'tanggallahir' => '1984-03-21', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000503', 'keluarga_id' => '0005', 'nama' => 'dedi setiawan', 'alias' => 'dedi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'semarang', 'tanggallahir' => '2010-08-01', 'hubungankeluarga' => 'anak', 'namaayah' => 'wahyu setiawan', 'namaibu' => 'rina setiawan', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000601', 'keluarga_id' => '0006', 'nama' => 'dedi suryadi', 'alias' => 'dedi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1977-03-15', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000602', 'keluarga_id' => '0006', 'nama' => 'tuti suryadi', 'alias' => 'tuti', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1980-07-05', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000603', 'keluarga_id' => '0006', 'nama' => 'rina suryadi', 'alias' => 'rina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '2005-02-22', 'hubungankeluarga' => 'anak', 'namaayah' => 'dedi suryadi', 'namaibu' => 'tuti suryadi', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000701', 'keluarga_id' => '0007', 'nama' => 'yudi hartono', 'alias' => 'yudi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'bandung', 'tanggallahir' => '1975-12-17', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000702', 'keluarga_id' => '0007', 'nama' => 'dini hartono', 'alias' => 'dini', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'bandung', 'tanggallahir' => '1977-04-16', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000703', 'keluarga_id' => '0007', 'nama' => 'nanda hartono', 'alias' => 'nanda', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'bandung', 'tanggallahir' => '2008-07-30', 'hubungankeluarga' => 'anak', 'namaayah' => 'yudi hartono', 'namaibu' => 'dini hartono', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000801', 'keluarga_id' => '0008', 'nama' => 'eko purwanto', 'alias' => 'eko', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'yogyakarta', 'tanggallahir' => '1980-01-28', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000802', 'keluarga_id' => '0008', 'nama' => 'rini purwanto', 'alias' => 'rini', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'yogyakarta', 'tanggallahir' => '1982-08-22', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000803', 'keluarga_id' => '0008', 'nama' => 'dinda purwanto', 'alias' => 'dinda', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'yogyakarta', 'tanggallahir' => '2009-10-04', 'hubungankeluarga' => 'anak', 'namaayah' => 'eko purwanto', 'namaibu' => 'rini purwanto', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000901', 'keluarga_id' => '0009', 'nama' => 'arif wibowo', 'alias' => 'arif', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1979-02-19', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000902', 'keluarga_id' => '0009', 'nama' => 'tina wibowo', 'alias' => 'tina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1981-06-15', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '000903', 'keluarga_id' => '0009', 'nama' => 'dina wibowo', 'alias' => 'dina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '2006-09-20', 'hubungankeluarga' => 'anak', 'namaayah' => 'arif wibowo', 'namaibu' => 'tina wibowo', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001001', 'keluarga_id' => '0010', 'nama' => 'sutrisno', 'alias' => 'sutris', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1978-07-17', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001002', 'keluarga_id' => '0010', 'nama' => 'lina sutrisno', 'alias' => 'lina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1980-05-13', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001003', 'keluarga_id' => '0010', 'nama' => 'fajar sutrisno', 'alias' => 'fajar', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'jakarta', 'tanggallahir' => '2011-04-07', 'hubungankeluarga' => 'anak', 'namaayah' => 'sutrisno', 'namaibu' => 'lina sutrisno', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001101', 'keluarga_id' => '0011', 'nama' => 'bayu pratama', 'alias' => 'bayu', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'bandung', 'tanggallahir' => '1985-03-19', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001102', 'keluarga_id' => '0011', 'nama' => 'mira pratama', 'alias' => 'mira', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'bandung', 'tanggallahir' => '1987-06-20', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001103', 'keluarga_id' => '0011', 'nama' => 'deni pratama', 'alias' => 'deni', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'bandung', 'tanggallahir' => '2008-11-23', 'hubungankeluarga' => 'anak', 'namaayah' => 'bayu pratama', 'namaibu' => 'mira pratama', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001201', 'keluarga_id' => '0012', 'nama' => 'herman suryadi', 'alias' => 'herman', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'medan', 'tanggallahir' => '1984-04-02', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001202', 'keluarga_id' => '0012', 'nama' => 'wina suryadi', 'alias' => 'wina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'medan', 'tanggallahir' => '1987-07-09', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001203', 'keluarga_id' => '0012', 'nama' => 'rini suryadi', 'alias' => 'rini', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'medan', 'tanggallahir' => '2010-01-12', 'hubungankeluarga' => 'anak', 'namaayah' => 'herman suryadi', 'namaibu' => 'wina suryadi', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001301', 'keluarga_id' => '0013', 'nama' => 'doni saputra', 'alias' => 'doni', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1977-08-14', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001302', 'keluarga_id' => '0013', 'nama' => 'siti saputra', 'alias' => 'siti', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1980-05-18', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001303', 'keluarga_id' => '0013', 'nama' => 'lina saputra', 'alias' => 'lina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '2009-09-19', 'hubungankeluarga' => 'anak', 'namaayah' => 'doni saputra', 'namaibu' => 'siti saputra', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001401', 'keluarga_id' => '0014', 'nama' => 'irwan santoso', 'alias' => 'irwan', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'semarang', 'tanggallahir' => '1983-02-17', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001402', 'keluarga_id' => '0014', 'nama' => 'tina santoso', 'alias' => 'tina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'semarang', 'tanggallahir' => '1986-08-14', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001403', 'keluarga_id' => '0014', 'nama' => 'anita santoso', 'alias' => 'anita', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'semarang', 'tanggallahir' => '2005-12-09', 'hubungankeluarga' => 'anak', 'namaayah' => 'irwan santoso', 'namaibu' => 'tina santoso', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001501', 'keluarga_id' => '0015', 'nama' => 'anton hidayat', 'alias' => 'anton', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1982-03-18', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001502', 'keluarga_id' => '0015', 'nama' => 'mira hidayat', 'alias' => 'mira', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1985-07-25', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001503', 'keluarga_id' => '0015', 'nama' => 'nando hidayat', 'alias' => 'nando', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'jakarta', 'tanggallahir' => '2012-05-14', 'hubungankeluarga' => 'anak', 'namaayah' => 'anton hidayat', 'namaibu' => 'mira hidayat', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001601', 'keluarga_id' => '0016', 'nama' => 'joko susanto', 'alias' => 'joko', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'bandung', 'tanggallahir' => '1984-11-23', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001602', 'keluarga_id' => '0016', 'nama' => 'dinda susanto', 'alias' => 'dinda', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'bandung', 'tanggallahir' => '1987-06-16', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001603', 'keluarga_id' => '0016', 'nama' => 'andi susanto', 'alias' => 'andi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'bandung', 'tanggallahir' => '2006-09-22', 'hubungankeluarga' => 'anak', 'namaayah' => 'joko susanto', 'namaibu' => 'dinda susanto', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001701', 'keluarga_id' => '0017', 'nama' => 'sugianto', 'alias' => 'sugi', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'yogyakarta', 'tanggallahir' => '1979-10-16', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001702', 'keluarga_id' => '0017', 'nama' => 'lina sugianto', 'alias' => 'lina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'yogyakarta', 'tanggallahir' => '1982-03-18', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001703', 'keluarga_id' => '0017', 'nama' => 'dina sugianto', 'alias' => 'dina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'yogyakarta', 'tanggallahir' => '2010-07-08', 'hubungankeluarga' => 'anak', 'namaayah' => 'sugianto', 'namaibu' => 'lina sugianto', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001801', 'keluarga_id' => '0018', 'nama' => 'wawan setiawan', 'alias' => 'wawan', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1977-02-19', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001802', 'keluarga_id' => '0018', 'nama' => 'rina setiawan', 'alias' => 'rina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '1980-06-15', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001803', 'keluarga_id' => '0018', 'nama' => 'nanda setiawan', 'alias' => 'nanda', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'surabaya', 'tanggallahir' => '2009-03-12', 'hubungankeluarga' => 'anak', 'namaayah' => 'wawan setiawan', 'namaibu' => 'rina setiawan', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001901', 'keluarga_id' => '0019', 'nama' => 'dani hidayat', 'alias' => 'dani', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'semarang', 'tanggallahir' => '1981-01-18', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001902', 'keluarga_id' => '0019', 'nama' => 'siti hidayat', 'alias' => 'siti', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'semarang', 'tanggallahir' => '1984-04-22', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '001903', 'keluarga_id' => '0019', 'nama' => 'fajar hidayat', 'alias' => 'fajar', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'semarang', 'tanggallahir' => '2012-09-15', 'hubungankeluarga' => 'anak', 'namaayah' => 'dani hidayat', 'namaibu' => 'siti hidayat', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '002001', 'keluarga_id' => '0020', 'nama' => 'yoga pratama', 'alias' => 'yoga', 'jeniskelamin' => 'laki-laki', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1979-06-16', 'hubungankeluarga' => 'kepala keluarga', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '002002', 'keluarga_id' => '0020', 'nama' => 'rini pratama', 'alias' => 'rini', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '1981-08-18', 'hubungankeluarga' => 'istri', 'namaayah' => '', 'namaibu' => '', 'statusbaptis' => 'sudah baptis', 'statussidi' => 'sudah sidi', 'statusnikah' => 'sudah menikah', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],
            ['stambuk' => '002003', 'keluarga_id' => '0020', 'nama' => 'dina pratama', 'alias' => 'dina', 'jeniskelamin' => 'perempuan', 'tempatlahir' => 'jakarta', 'tanggallahir' => '2008-11-12', 'hubungankeluarga' => 'anak', 'namaayah' => 'yoga pratama', 'namaibu' => 'rini pratama', 'statusbaptis' => 'sudah baptis', 'statussidi' => '', 'statusnikah' => '', 'pendidikan' => 'tidak/belum sekolah', 'pekerjaan' => 'tidak/belum bekerja', 'tanggaldaftar' => null, 'hp' => '', 'status' => 'aktif'],

        ]);
    }
}
