<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KecamatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kecamatan')->insert([
            ['id' => '1', 'kabupaten_id' => '1', 'nama' => 'cibeber'],
            ['id' => '2', 'kabupaten_id' => '1', 'nama' => 'cilegon'],
            ['id' => '3', 'kabupaten_id' => '1', 'nama' => 'citangkil'],
            ['id' => '4', 'kabupaten_id' => '1', 'nama' => 'ciwandan'],
            ['id' => '5', 'kabupaten_id' => '1', 'nama' => 'gerogol'],
            ['id' => '6', 'kabupaten_id' => '1', 'nama' => 'jombang'],
            ['id' => '7', 'kabupaten_id' => '1', 'nama' => 'pulomerak'],
            ['id' => '8', 'kabupaten_id' => '1', 'nama' => 'purwakarta'],
            ['id' => '9', 'kabupaten_id' => '2', 'nama' => 'banjarsari'],
            ['id' => '10', 'kabupaten_id' => '2', 'nama' => 'bayah'],
            ['id' => '11', 'kabupaten_id' => '2', 'nama' => 'bojongmanik'],
            ['id' => '12', 'kabupaten_id' => '2', 'nama' => 'cibadak'],
            ['id' => '13', 'kabupaten_id' => '2', 'nama' => 'cibeber'],
            ['id' => '14', 'kabupaten_id' => '2', 'nama' => 'cigemlong'],
            ['id' => '15', 'kabupaten_id' => '2', 'nama' => 'cihara'],
            ['id' => '16', 'kabupaten_id' => '2', 'nama' => 'cijaku'],
            ['id' => '17', 'kabupaten_id' => '2', 'nama' => 'cikulur'],
            ['id' => '18', 'kabupaten_id' => '2', 'nama' => 'cileles'],
            ['id' => '19', 'kabupaten_id' => '2', 'nama' => 'cilograng'],
            ['id' => '20', 'kabupaten_id' => '2', 'nama' => 'cimarga'],
            ['id' => '21', 'kabupaten_id' => '2', 'nama' => 'cipanas'],
            ['id' => '22', 'kabupaten_id' => '2', 'nama' => 'cirinten'],
            ['id' => '23', 'kabupaten_id' => '2', 'nama' => 'curug bitung'],
            ['id' => '24', 'kabupaten_id' => '2', 'nama' => 'gunung kencana'],
            ['id' => '25', 'kabupaten_id' => '2', 'nama' => 'kalanganyar'],
            ['id' => '26', 'kabupaten_id' => '2', 'nama' => 'lebak gedong'],
            ['id' => '27', 'kabupaten_id' => '2', 'nama' => 'leuwidamar'],
            ['id' => '28', 'kabupaten_id' => '2', 'nama' => 'maja'],
            ['id' => '29', 'kabupaten_id' => '2', 'nama' => 'malingping'],
            ['id' => '30', 'kabupaten_id' => '2', 'nama' => 'muncang'],
            ['id' => '31', 'kabupaten_id' => '2', 'nama' => 'panggarangan'],
            ['id' => '32', 'kabupaten_id' => '2', 'nama' => 'rangkasbitung'],
            ['id' => '33', 'kabupaten_id' => '2', 'nama' => 'sajira'],
            ['id' => '34', 'kabupaten_id' => '2', 'nama' => 'sobang'],
            ['id' => '35', 'kabupaten_id' => '2', 'nama' => 'wanasalam'],
            ['id' => '36', 'kabupaten_id' => '2', 'nama' => 'warung gunung'],
            ['id' => '37', 'kabupaten_id' => '3', 'nama' => 'angsana'],
            ['id' => '38', 'kabupaten_id' => '3', 'nama' => 'banjar'],
            ['id' => '39', 'kabupaten_id' => '3', 'nama' => 'bojong'],
            ['id' => '40', 'kabupaten_id' => '3', 'nama' => 'cadasari'],
            ['id' => '41', 'kabupaten_id' => '3', 'nama' => 'carita'],
            ['id' => '42', 'kabupaten_id' => '3', 'nama' => 'cibaliung'],
            ['id' => '43', 'kabupaten_id' => '3', 'nama' => 'cibitung'],
            ['id' => '44', 'kabupaten_id' => '3', 'nama' => 'cigeulis'],
            ['id' => '45', 'kabupaten_id' => '3', 'nama' => 'cikeudal'],
            ['id' => '46', 'kabupaten_id' => '3', 'nama' => 'cikeusik'],
            ['id' => '47', 'kabupaten_id' => '3', 'nama' => 'cimanggu'],
            ['id' => '48', 'kabupaten_id' => '3', 'nama' => 'cimanuk'],
            ['id' => '49', 'kabupaten_id' => '3', 'nama' => 'cipeucang'],
            ['id' => '50', 'kabupaten_id' => '3', 'nama' => 'cisata'],
            ['id' => '51', 'kabupaten_id' => '3', 'nama' => 'jiput'],
            ['id' => '52', 'kabupaten_id' => '3', 'nama' => 'kaduhejo'],
            ['id' => '53', 'kabupaten_id' => '3', 'nama' => 'karang tanjung'],
            ['id' => '54', 'kabupaten_id' => '3', 'nama' => 'koroncong'],
            ['id' => '55', 'kabupaten_id' => '3', 'nama' => 'labuan'],
            ['id' => '56', 'kabupaten_id' => '3', 'nama' => 'majasari'],
            ['id' => '57', 'kabupaten_id' => '3', 'nama' => 'mandalawangi'],
            ['id' => '58', 'kabupaten_id' => '3', 'nama' => 'mekarjaya'],
            ['id' => '59', 'kabupaten_id' => '3', 'nama' => 'menes'],
            ['id' => '60', 'kabupaten_id' => '3', 'nama' => 'munjul'],
            ['id' => '61', 'kabupaten_id' => '3', 'nama' => 'pagelaran'],
            ['id' => '62', 'kabupaten_id' => '3', 'nama' => 'pandeglang'],
            ['id' => '63', 'kabupaten_id' => '3', 'nama' => 'panimbang'],
            ['id' => '64', 'kabupaten_id' => '3', 'nama' => 'patia'],
            ['id' => '65', 'kabupaten_id' => '3', 'nama' => 'picung'],
            ['id' => '66', 'kabupaten_id' => '3', 'nama' => 'pulosari'],
            ['id' => '67', 'kabupaten_id' => '3', 'nama' => 'saketi'],
            ['id' => '68', 'kabupaten_id' => '3', 'nama' => 'sindangresmi'],
            ['id' => '69', 'kabupaten_id' => '3', 'nama' => 'sobang'],
            ['id' => '70', 'kabupaten_id' => '3', 'nama' => 'sukaresmi'],
            ['id' => '71', 'kabupaten_id' => '3', 'nama' => 'sumur'],
            ['id' => '72', 'kabupaten_id' => '4', 'nama' => 'cipocok jaya'],
            ['id' => '73', 'kabupaten_id' => '4', 'nama' => 'curug'],
            ['id' => '74', 'kabupaten_id' => '4', 'nama' => 'kasemen'],
            ['id' => '75', 'kabupaten_id' => '4', 'nama' => 'serang'],
            ['id' => '76', 'kabupaten_id' => '4', 'nama' => 'taktakan'],
            ['id' => '77', 'kabupaten_id' => '4', 'nama' => 'walantaka'],
            ['id' => '78', 'kabupaten_id' => '5', 'nama' => 'anyar'],
            ['id' => '79', 'kabupaten_id' => '5', 'nama' => 'bandung'],
            ['id' => '80', 'kabupaten_id' => '5', 'nama' => 'baros'],
            ['id' => '81', 'kabupaten_id' => '5', 'nama' => 'binuang'],
            ['id' => '82', 'kabupaten_id' => '5', 'nama' => 'bojonegara'],
            ['id' => '83', 'kabupaten_id' => '5', 'nama' => 'carenang'],
            ['id' => '84', 'kabupaten_id' => '5', 'nama' => 'cikande'],
            ['id' => '85', 'kabupaten_id' => '5', 'nama' => 'cikeusal'],
            ['id' => '86', 'kabupaten_id' => '5', 'nama' => 'cinangka'],
            ['id' => '87', 'kabupaten_id' => '5', 'nama' => 'ciomas'],
            ['id' => '88', 'kabupaten_id' => '5', 'nama' => 'ciruas'],
            ['id' => '89', 'kabupaten_id' => '5', 'nama' => 'gunung sari'],
            ['id' => '90', 'kabupaten_id' => '5', 'nama' => 'jawilan'],
            ['id' => '91', 'kabupaten_id' => '5', 'nama' => 'kibin'],
            ['id' => '92', 'kabupaten_id' => '5', 'nama' => 'kopo'],
            ['id' => '93', 'kabupaten_id' => '5', 'nama' => 'kragilan'],
            ['id' => '94', 'kabupaten_id' => '5', 'nama' => 'kramatwatu'],
            ['id' => '95', 'kabupaten_id' => '5', 'nama' => 'lebak wangi'],
            ['id' => '96', 'kabupaten_id' => '5', 'nama' => 'mancak'],
            ['id' => '97', 'kabupaten_id' => '5', 'nama' => 'pabuaran'],
            ['id' => '98', 'kabupaten_id' => '5', 'nama' => 'padarincang'],
            ['id' => '99', 'kabupaten_id' => '5', 'nama' => 'pamarayan'],
            ['id' => '100', 'kabupaten_id' => '5', 'nama' => 'petir'],
            ['id' => '101', 'kabupaten_id' => '5', 'nama' => 'pontang'],
            ['id' => '102', 'kabupaten_id' => '5', 'nama' => 'pulo ampel'],
            ['id' => '103', 'kabupaten_id' => '5', 'nama' => 'tanara'],
            ['id' => '104', 'kabupaten_id' => '5', 'nama' => 'tirtayasa'],
            ['id' => '105', 'kabupaten_id' => '5', 'nama' => 'tunjung teja'],
            ['id' => '106', 'kabupaten_id' => '5', 'nama' => 'waringin kurung'],
            ['id' => '107', 'kabupaten_id' => '6', 'nama' => 'batuceper'],
            ['id' => '108', 'kabupaten_id' => '6', 'nama' => 'benda'],
            ['id' => '109', 'kabupaten_id' => '6', 'nama' => 'cibodas'],
            ['id' => '110', 'kabupaten_id' => '6', 'nama' => 'ciledug'],
            ['id' => '111', 'kabupaten_id' => '6', 'nama' => 'cipondoh'],
            ['id' => '112', 'kabupaten_id' => '6', 'nama' => 'jatiuwung'],
            ['id' => '113', 'kabupaten_id' => '6', 'nama' => 'karang tengah'],
            ['id' => '114', 'kabupaten_id' => '6', 'nama' => 'karawaci'],
            ['id' => '115', 'kabupaten_id' => '6', 'nama' => 'larangan'],
            ['id' => '116', 'kabupaten_id' => '6', 'nama' => 'neglasari'],
            ['id' => '117', 'kabupaten_id' => '6', 'nama' => 'periuk'],
            ['id' => '118', 'kabupaten_id' => '6', 'nama' => 'pinang (penang)'],
            ['id' => '119', 'kabupaten_id' => '6', 'nama' => 'tangerang'],
            ['id' => '120', 'kabupaten_id' => '7', 'nama' => 'balaraja'],
            ['id' => '121', 'kabupaten_id' => '7', 'nama' => 'cikupa'],
            ['id' => '122', 'kabupaten_id' => '7', 'nama' => 'cisauk'],
            ['id' => '123', 'kabupaten_id' => '7', 'nama' => 'cisoka'],
            ['id' => '124', 'kabupaten_id' => '7', 'nama' => 'curug'],
            ['id' => '125', 'kabupaten_id' => '7', 'nama' => 'gunung kaler'],
            ['id' => '126', 'kabupaten_id' => '7', 'nama' => 'jambe'],
            ['id' => '127', 'kabupaten_id' => '7', 'nama' => 'jayanti'],
            ['id' => '128', 'kabupaten_id' => '7', 'nama' => 'kelapa dua'],
            ['id' => '129', 'kabupaten_id' => '7', 'nama' => 'kemiri'],
            ['id' => '130', 'kabupaten_id' => '7', 'nama' => 'kosambi'],
            ['id' => '131', 'kabupaten_id' => '7', 'nama' => 'kresek'],
            ['id' => '132', 'kabupaten_id' => '7', 'nama' => 'kronjo'],
            ['id' => '133', 'kabupaten_id' => '7', 'nama' => 'legok'],
            ['id' => '134', 'kabupaten_id' => '7', 'nama' => 'mauk'],
            ['id' => '135', 'kabupaten_id' => '7', 'nama' => 'mekar baru'],
            ['id' => '136', 'kabupaten_id' => '7', 'nama' => 'pagedangan'],
            ['id' => '137', 'kabupaten_id' => '7', 'nama' => 'pakuhaji'],
            ['id' => '138', 'kabupaten_id' => '7', 'nama' => 'panongan'],
            ['id' => '139', 'kabupaten_id' => '7', 'nama' => 'pasar kemis'],
            ['id' => '140', 'kabupaten_id' => '7', 'nama' => 'rajeg'],
            ['id' => '141', 'kabupaten_id' => '7', 'nama' => 'sepatan'],
            ['id' => '142', 'kabupaten_id' => '7', 'nama' => 'sepatan timur'],
            ['id' => '143', 'kabupaten_id' => '7', 'nama' => 'sindang jaya'],
            ['id' => '144', 'kabupaten_id' => '7', 'nama' => 'solear'],
            ['id' => '145', 'kabupaten_id' => '7', 'nama' => 'sukadiri'],
            ['id' => '146', 'kabupaten_id' => '7', 'nama' => 'sukamulya'],
            ['id' => '147', 'kabupaten_id' => '7', 'nama' => 'teluknaga'],
            ['id' => '148', 'kabupaten_id' => '7', 'nama' => 'tigaraksa'],
            ['id' => '149', 'kabupaten_id' => '8', 'nama' => 'ciputat'],
            ['id' => '150', 'kabupaten_id' => '8', 'nama' => 'ciputat timur'],
            ['id' => '151', 'kabupaten_id' => '8', 'nama' => 'pamulang'],
            ['id' => '152', 'kabupaten_id' => '8', 'nama' => 'pondok aren'],
            ['id' => '153', 'kabupaten_id' => '8', 'nama' => 'serpong'],
            ['id' => '154', 'kabupaten_id' => '8', 'nama' => 'serpong utara'],
            ['id' => '155', 'kabupaten_id' => '8', 'nama' => 'setu']
        ]);
    }
}
